import {StyleSheet} from 'react-native';
import {COLORS} from '../../utils/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  containerTable: {
    flex: 1,
    backgroundColor: 'white',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: '#f9f0eb',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginHorizontal: 15,
    marginTop: 10,
  },
  headerText: {
    fontWeight: 'bold',
    color: '#a30000',
    width: '30%',
    textAlign: 'left',
  },
  card: {
    backgroundColor: COLORS.GREY,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY,
    margin: 10,
    borderRadius: 8,
    elevation: 3,
    shadowColor: 'transparent',
    shadowOpacity: 0,
    marginVertical: 6,
    borderWidth: 0.5,
    borderColor: '#e0e0e0',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 8,
    backgroundColor: COLORS.LIGHT_PRIMARY,
  },
  cardHeaderText: {
    fontWeight: 'bold',
    color: '#a30000',
    width: '30%',
    textAlign: 'center',
  },
  row: {
    flexDirection: 'row',
    padding: 10,
    justifyContent: 'space-between',
  },
  cellText: {
    width: '30%',
    fontSize: 12,
    color: '#000',
    textAlign: 'center',
  },
  fab: {
    backgroundColor: COLORS.PRIMARY,
    width: 50,
    height: 50,
    borderRadius: 25,
    position: 'absolute',
    right: 30,
    bottom: 50,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },
  modal: {
    backgroundColor: COLORS.PRIMARY,
    padding: 0,
    margin: 20,
    borderRadius: 10,
  },
  input: {
    marginBottom: 10,
    backgroundColor: 'white',
  },
  dropdown: {
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 12,
    marginBottom: 10,
  },
});
