export const COMMON_STYLES = {
  SCREEN_VERTICAL_SPACING: 50,
  SCREEN_VERTICAL_TABLE_SPACING: 100,
  SCREEN_HORIZONTAL_SPACING: 20,
  SCREEN_HORIZONTAL_TABLE_SPACING: 50,
  FONT_REGULAR: 'Poppins-Regular',
  FONT_BOLD: 'Poppins-Bold',
  FONT_MEDIUM: 'Poppins-Medium',
  DANCE_STYLE: 'DancingScript-Bold',
};
