export const SCREENS = {
  MAIN_STACK: {
    SPLASH: 'SPLASH',
    LOGIN: 'LOGIN',
    SELECT_DEALER_CODE: 'SELECT_DEALER_CODE',
    DVR_SCORE: 'DVR_SCORE',
    COMPLAINTS_ANALYSIS: 'COMPLAINTS_ANALYSIS',
    KPI_PERFORMANCE: 'KPI_PERFORMANCE',
    MAN_POWER_STATUS: 'MAN_POWER_STATUS',
    MINUTES_OF_MEETING: 'MINUTES_OF_MEETING',
    COMPLETE_FORM: 'COMPLETE_FORM',
    KEY_ACTIVITIES: 'KEY_ACTIVITIES',
    SERVICE_ATTRIBUTES: 'SERVICE_ATTRIBUTES',
    ATTRIBUTES: 'ATTRIBUTES',
    REPEAT_JOB: 'REPEAT_JOB',
    ACCOMPANIED_COMPANY: 'ACCOMPANIED_COMPANY',
    ACCOMPANIED_DEALER: 'ACCOMPANIED_DEALER',
  },
  DRAWER_STACK: {
    DASHBOARD: 'DASHBOARD',
    LOGOUT: 'LOGOUT',
  },
};
